biome.json
-> Adding rules for camelCase in biome.json file
-> related to #27 
cc: @seveibar
=> Stricting camelCase

fake-snippets-api/lib/db/seed.ts, src/components/CodeAndPreview.tsx, src/hooks/use-run-tsx/construct-circuit.tsx, src/hooks/use-run-tsx/eval-compiled-js.ts, src/hooks/use-run-tsx/index.tsx, src/pages/quickstart.tsx
Also fixes dashboard always loading from hardcoded "seveibar/"
=> Import Runner Part 1

src/components/EditorNav.tsx, src/hooks/use-create-snippet-mutation.ts, src/lib/encodeTextToUrlHash.ts
Issue: #129
- Updated encodeTextToUrlHash to add snippet type to the URL.
- If not explicitly specified : Defaults to board if <board is detected in code; otherwise package.
=> adds snippet type to the url for copy url

src/components/ViewSnippetSidebar.tsx, src/hooks/use-copy-to-clipboard.ts
This fix is resolving issue with copy to clipboard on the snippets page.
Related to #180
=> fix(#180): Added copy to clipboard functionality

fake-snippets-api/lib/db/schema.ts, fake-snippets-api/routes/api/snippets/create.ts, fake-snippets-api/routes/api/snippets/update.ts, src/components/CodeAndPreview.tsx, src/components/EditorNav.tsx, src/hooks/use-create-snippet-mutation.ts, src/hooks/use-save-snippet.ts
Issue: #198 
Updates in schema, when the snippet is saved. circuitJson generated on running is directly passed for mutation.
One issue i ran into was, if i tried to save a modified snippet which is not run. As circuit json isnt generated yet, there is inconsistencies between circuit_json and current code. I tried to generate circuit_json on clicking save, for mutation, but couldn't figure it out for a long time.
Temporary solution implemented: disable save button, if code is updated and not ran
cc: @seveibar
=> Added circuit_json to snippet schema

src/components/CodeEditor.tsx
fixes: #158 
removed unncessary dispatch which causes the editor to update the content of the editor, and makes the cursor go at line 0.
the update happens regardless of whether the content has actually changed.
=> fix: cursor-pos

src/components/ViewSnippetSidebar.tsx
continuation of #171
updated embed link with /preview
cc: @seveibar
=> Update link for iframe embedding of snippets

src/components/CodeAndPreview.tsx
`manualEditsFileContent` wasn;t being initialized with the manual_edit_json when the page loaded, so the issue was when we tried to look for `hasUnsavedChanges` it always resulted in true, and that's the reason it displayed "Unsaved Changes"
fixes: #265 
sorry for this bug too. cc: @seveibar
=> fix: load manual_json

src/hooks/use-sign-in.ts
Fixes the `invalid_code_token ` issue
=> fix: auth generate fails when not using `localhost`

src/components/CodeAndPreview.tsx, src/components/CodeEditor.tsx
/close #394 
The manual edit template was not getting imported anywhere and because of that the Eval import throws error because of empty string.
=> fix: Use the template at initialization

src/components/CodeAndPreview.tsx, src/components/CodeEditor.tsx
Reverts tscircuit/snippets#413
@imrishabh18 this caused a bug where an Error is shown on every snippet.
I also am not sure that we want to have every snippet require a manual edits file, it should be optional. If it's an empty string/null that means there isn't one set yet
=> Revert "fix: Use the template at initialization"

src/hooks/use-run-tsx/index.tsx
This is the better approach as we are moving to the "pure snippets", I think we shouldn't be throwing error on importing empty file for manual-edits
=> fix: import manual edits

src/components/EditorNav.tsx
The EditorNav Component will be aligned to the right side
Responsive device check ✅
/claim #402
=> fix: Responsive Align-header on right #404

src/pages/landing.tsx
fixes #477 
fix landing page card alignment
@seveibar now working well
=> fix landing page card allignment

src/components/ViewSnippetHeader.tsx
=> fix star button working

src/components/PrefetchPageLink.tsx
- get component name from link
- when the link is "/editor?template=blank-circuit-module" prefetch "editor.tsx" component
=> prefetch fix

.github/workflows/bundle-size-analysis.yml
=> ci(bundle-size-analysis): updated external actions

api/generated-index.js
This fix kind of sucks because it degrades the performance of the pages, but we would have to implement refresh logic in index.html that detects when a new deployment occurs to fix this
basically we need the index.html to detect if it's an old deployment, then force refresh the page
=> alter cache control to not cache html too long, causing white pages and forced refresh sometimes

src/components/DownloadButtonAndMenu.tsx
Wrap the disabled button in a div to improve structure and use `asChild` for DropdownMenuTrigger to ensure proper component composition
=> refactor(DownloadButtonAndMenu): wrap disabled button in div &use asChild for DropdownMenuTrigger

src/App.tsx, src/pages/404.tsx, src/pages/view-package.tsx
Add a new 404 page to handle cases where users navigate to non-existent routes or packages. Implement logic in the ViewPackagePage to detect missing packages and redirect to the 404 page. This improves user experience by providing clear feedback when resources are not found.
=> feat(routing): add 404 page and handle not found states

fake-snippets-api/routes/api/snippets/list_trending.ts, src/App.tsx, src/components/Footer.tsx, src/components/SnippetCard.tsx, src/pages/trending.tsx, src/pages/user-profile.tsx
Introduce a new page to showcase the most popular snippets from the last 7 days. The page includes a loading state, error handling, and a grid layout for displaying snippets with their star counts and creation dates. This enhances user engagement by providing insights into trending content.
_outdated text below_
---
=> feat: add trending page to display popular snippets

src/components/Footer.tsx
The "Create with AI" link was moved from the list of navigation items to a standalone link in the footer. This change improves the layout and ensures the link opens in a new tab for better user experience.
https://github.com/user-attachments/assets/4427e452-121c-43f6-b36e-8fabac791579
=> refactor(Footer): remove "Create with AI" from list and add as standalone link

bun-tests/fake-snippets-api/routes/package_files/create_or_update.test.ts, bun-tests/fake-snippets-api/routes/package_files/delete.test.ts, fake-snippets-api/lib/db/db-client.ts, fake-snippets-api/lib/db/schema.ts, fake-snippets-api/routes/api/package_files/create_or_update.ts, fake-snippets-api/routes/api/package_files/delete.ts
Introduce new functionality to create, update, and delete package files. This includes:
- Adding new fields to the package file schema (`content_mimetype`, `is_release_tarball`, `npm_pack_output`).
- Implementing `deletePackageFile` and `updatePackageFile` methods in the DB client.
- Creating new API routes for file deletion and creation/updating.
- Adding comprehensive tests for the new functionality.
fix #830
=> feat(package_files): add CRUD operations for package files

src/components/dialogs/edit-package-details-dialog.tsx
- remove redundant parameters passed in the JsonBody of API calls
- remove whole page reload for just license update
=> refactor the license hooks

src/components/ViewPackagePage/components/important-files-view.tsx, src/components/ViewPackagePage/components/package-header.tsx
- Add `overflow-x-auto` to `ShikiCodeViewer` container for better handling of long code lines
- Refactor `PackageHeader` layout for improved responsiveness with flex-wrap and breakpoints
- Enhance link styling with hover effects and break-word handling for long package names
- Add mobile-specific button layout for better usability on smaller screens
=> style(components): improve responsiveness and styling in package header and code viewer

src/components/FileSidebar.tsx, src/components/ui/tree-view.tsx
fix #876 
fix #881
refactor(FileSidebar): improve tree data transformation logic and handle hidden files
- Fix syntax error in `selectedTreeVariants` by removing an extra single quote
- Add `useEffect` to sync `selectedItemId` with `initialSelectedItemId` in `TreeView`
- Refactor `transformFilesToTreeData` to handle paths starting with a slash and filter hidden files
- Convert nested object structure to array structure for tree data
=> fix(tree-view): correct syntax error in selectedTreeVariants and sync selected item

src/components/package-port/CodeEditor.tsx
The ATA (Automatic Type Acquisition) initialization was previously limited to `index.tsx`. This change extends it to include all `.tsx` and `.ts` files, ensuring type acquisition works consistently across all TypeScript files.
related to #828
=> refactor(CodeEditor): "tscircuit" alias for core && expand ATA run condition to include .ts files

src/components/CodeEditor.tsx, src/components/package-port/CodeEditor.tsx
=> Fix the overflow and tooltip ui when hovering over code components

src/components/SearchComponent.tsx
Add a useRef hook to the input element and focus it on component mount to enhance user experience by immediately allowing keyboard input
resolve #894
https://github.com/user-attachments/assets/6b181121-caa7-4bdd-bd2e-ab933200db46
=> feat(SearchComponent): focus input on mount to improve UX

src/components/ViewPackagePage/components/markdown-viewer.tsx
=> Change syntax highlighting for markdown to tsx

src/components/Header2.tsx, src/components/SearchComponent.tsx
The autofocus prop allows conditional focus on the search input, improving user experience by focusing only when explicitly needed
resolve #960
=> feat(SearchComponent): add autofocus prop to control input focus

src/pages/dashboard.tsx
=> If a user goes to /dashboard, show them an empty state that tells them to login

src/components/package-port/CodeAndPreview.tsx, src/components/package-port/EditorNav.tsx
The condition for rendering the loading state was incomplete, causing the component to render prematurely. Added `isLoadingFiles` to the condition to ensure the loading state is displayed correctly while files are being loaded.
resolve #939
=> fix: add isLoadingFiles check to prevent premature rendering

src/components/package-port/CodeEditor.tsx
The commit ensures that paths in the `fsMap` are consistently prefixed with a forward slash if they don't already start with one. This prevents potential issues with path resolution in the virtual file system. Additionally, a debug log statement was added to inspect the keys of the `fsMap` for troubleshooting purposes.
close #948
=> fix(CodeEditor): ensure consistent path handling in fsMap

src/components/package-port/EditorNav.tsx
Add a keyboard shortcut (Ctrl/Cmd + S) to trigger the save functionality in the EditorNav component. This enhances user experience by allowing quick saves without manually clicking the save button.
fix #981
=> feat(EditorNav): add keyboard shortcut to save package

src/components/package-port/CodeEditor.tsx
Update the tooltip text from "Ctrl/Cmd+Click to open snippet" to "Ctrl/Cmd+Click to open package" for accuracy. Additionally, preserve the scroll position when updating the editor content to improve user experience.
=> fix(CodeEditor): correct tooltip text and preserve scroll position

src/components/package-port/CodeAndPreview.tsx
The logic for handling package visibility changes was duplicated in both the `handleSave` function and the `onSave` callback of `PackageVisibilitySettingsDialog`. This commit extracts this logic into a separate `handlePkgVisibilityChange` function to improve code maintainability and reduce redundancy.
=> refactor(CodeAndPreview): fix package files not saving for new package

src/components/ViewPackagePage/components/important-files-view.tsx
Add a copy button to the important files view component to allow users to copy the content of the active file. The button toggles between "copy" and "copied" states for better user feedback. This enhances the usability of the component by providing a quick way to copy file content.
=> feat(important-files-view): add copy button for active file content

src/components/package-port/CodeAndPreview.tsx, src/components/package-port/EditorNav.tsx
The `hasUnrunChanges` prop was not used within the `EditorNav` component, so it has been removed to clean up the code and improve maintainability.
=> refactor(EditorNav): remove unused hasUnrunChanges prop

src/components/DownloadButtonAndMenu.tsx
- Added a toast with variant: "destructive" on download error.
- Displays a user-friendly title and the error message.
=> fix: Add destructive toast variant for download error

fake-snippets-api/lib/db/autoload-packages.json, src/components/package-port/CodeAndPreview.tsx
Adding back the previous deleted file to autoload packages
=> fix: Manual edits failing to render circuits having the `manual-edits.json` file

bun.lock, package.json
This commit updates the `circuit-json-to-gerber` dependency to version 0.0.18 to ensure compatibility with the latest changes and improvements in the library.
closes https://github.com/tscircuit/circuit-json-to-gerber/issues/30
=> chore: update circuit-json-to-gerber dependency to v0.0.18

src/components/package-port/CodeEditor.tsx
Introduce `isCodeEditorReady` state to manage editor opacity based on its readiness. This improves user experience by visually indicating when the editor is fully loaded and functional.
> ignore errors, fixed in my other prs
fix #1031
https://github.com/user-attachments/assets/9927437b-206a-4170-b375-51b2950bba1d
=> feat(CodeEditor): add state to track editor readiness

src/components/dialogs/confirm-delete-package-dialog.tsx, src/pages/user-profile.tsx
… 
fix #1053
This update modifies the ConfirmDeletePackageDialog to call refetchUserPackages after a package is successfully deleted, ensuring the user interface reflects the latest package data. The UserProfilePage is updated to pass the refetchUserPackages function to the DeleteDialog component.
https://github.com/user-attachments/assets/32e5070d-664a-47a4-a6ba-2be894e7769e
=> feat: enhance package deletion flow by refetching user packages after successful deletion

fake-snippets-api/routes/api/snippets/generate_from_jlcpcb.ts, src/components/JLCPCBImportDialog.tsx, src/pages/dashboard.tsx
… 
fix #1038
- Removed redundant error handling in fetch and conversion functions.
- Updated snippet creation to return the created snippet instead of a new object.
- Adjusted navigation links in JLCPCBImportDialog and DashboardPage to use `package_id` instead of `snippet_id`.
- Added a description to the JLCPCB import dialog for better user guidance.
- Sync with registry-api
=> refactor: streamline error handling and update snippet creation logic in JLCPCB component generation

src/components/FAQ.tsx
=> fix(refactor): question text in accordion on small devices

src/components/package-port/CodeAndPreview.tsx, src/components/package-port/CodeEditor.tsx, src/hooks/use-create-package-mutation.ts, src/hooks/useFileManagement.ts
…
fix #1198 
- disable CodeEditor when isSaving prop is true
- improve loading condition logic and increase loading screen height
- refactor package creation flow for better separation of concerns
- move URL management from mutation hook to file management hook
=> feat: disable code editor during save operations and improve package creation flow

src/components/ViewPackagePage/components/mobile-sidebar.tsx, src/components/ViewPackagePage/components/sidebar-about-section.tsx, src/components/dialogs/edit-package-details-dialog.tsx, src/hooks/use-package-details-form.ts
- Add unscopedPackageName field to dialog form
- Update form validation to track package name changes
- Implement package name update in API calls
- Add client-side URL navigation when package name changes
- Improve error handling with detailed error messages
- Add autoComplete="off" to form inputs
- Add spellCheck={false} to description textarea
=> feat: add package name editing to edit package details dialog

src/components/ViewPackagePage/components/important-files-view.tsx, src/components/ViewPackagePage/utils/is-package-file-important.ts
=> fix: ui of important file tabs overlapping

src/components/ui/dialog.tsx
=> fix(dialog):  enhance responsive design in dialog component & sync to theme

src/components/ViewPackagePage/components/important-files-view.tsx, src/components/ViewPackagePage/components/repo-page-content.tsx
This pull request introduces a security enhancement that limits the ability to generate or re-generate AI reviews to only the package owner. Previously, any authenticated user had access to this functionality.
---
* Added a `packageAuthorId` prop to the component.
* Replaced the `useUser` hook with `useGlobalStore` to retrieve the currently logged-in user's session info.
* Conditionally render the **"Request AI Review"** and **"Re-request AI Review"** buttons only when the logged-in user's `github_username` matches the `packageAuthorId`.
* Passed the `packageAuthorOwner` (sourced from `packageInfo.owner_github_username`) as a prop to the `ImportantFilesView` component.
=> feat: Restrict AI review generation to package owners

src/components/package-port/CodeEditorHeader.tsx
…
The component name was hardcoded as "C1" which caused incorrect component fetching. Now it uses the actual component.name from props.
=> fix(CodeEditorHeader): pass correct component name to fetchEasyEDAComponent

src/components/CmdKMenu.tsx
Add a star icon and count display next to package tags to show popularity metrics. The star count is taken from the data object and defaults to 0 if not available.
=> feat(CmdKMenu): add star count display for packages

fake-snippets-api/lib/db/schema.ts, fake-snippets-api/lib/public-mapping/public-map-package-release.ts, fake-snippets-api/lib/public-mapping/public-map-package.ts, fake-snippets-api/routes/api/packages/update.ts, src/components/ViewPackagePage/components/mobile-sidebar.tsx, src/components/ViewPackagePage/components/sidebar-about-section.tsx, src/components/dialogs/GitHubRepositorySelector.tsx, src/components/dialogs/edit-package-details-dialog.tsx, src/hooks/use-package-details-form.ts
- Add allow_pr_previews field to package schema and update API
- Pass currentAllowPrPreviews to edit dialog components
- Update GitHubRepositorySelector to use allowPrPreviews instead of enablePrPreview
- Include is_pr_preview and github_pr_number in package release mapping
=> feat(pr-previews): add support for PR previews in package settings

bun-tests/fake-snippets-api/routes/package_builds/get.test.ts, bun-tests/fake-snippets-api/routes/package_builds/list.test.ts, fake-snippets-api/lib/db/db-client.ts, fake-snippets-api/lib/db/schema.ts, fake-snippets-api/lib/db/seed.ts, fake-snippets-api/lib/public-mapping/public-map-package-build.ts, fake-snippets-api/lib/public-mapping/public-map-package-release.ts, src/App.tsx, src/components/PackageBreadcrumb.tsx, src/components/ViewPackagePage/components/sidebar-about-section.tsx, src/components/preview/BuildsList.tsx, src/components/preview/ConnectedPackagesList.tsx, src/components/preview/ConnectedRepoOverview.tsx, src/components/preview/PackageReleasesDashboard.tsx, src/components/preview/index.tsx, src/hooks/use-packages-base-api-url.ts, src/pages/preview-release.tsx, src/pages/release-detail.tsx, src/pages/releases.tsx
- Update schema to move branch_name, commit_message, and commit_author from PackageBuild to PackageRelease
- Update UI components to use release metadata instead of build metadata
- Fix route paths to use "releases" instead of "release"
- Remove mock package builds data
- Set default sidebar state to collapsed in preview page
- Ask user to connect github repo
=> refactor(releases): move git metadata from builds to releases

src/components/PackageBuildsPage/build-preview-content.tsx
=> feat(build-preview): add loading and error states for package build preview

fake-snippets-api/lib/db/schema.ts, src/components/DownloadButtonAndMenu.tsx, src/components/ViewPackagePage/components/main-content-header.tsx, src/components/ViewPackagePage/components/package-header.tsx, src/components/ViewPackagePage/components/repo-page-content.tsx, src/hooks/use-current-package-id.ts, src/hooks/use-current-package-info.ts, src/pages/view-package.tsx
Prevent duplicated `packages/get` requests.
Request `circuit.json` only when clicking download buttons. 
This pull request updates how circuit package downloads and starring functionality are handled in the UI, improving reliability and simplifying state management. The main changes include fetching `circuit.json` on demand for download actions, updating the download menu logic to support this, and refactoring the package starring logic to use data from the package info directly. Additionally, a new `is_starred` field was added to the package schema.
**Download logic improvements:**
* The `DownloadButtonAndMenu` component now fetches `circuit.json` on demand if not already available, using a new helper function and state to manage the fetched data. This ensures downloads work even when …
=> Optimize package/get Requests

src/components/ViewPackagePage/components/sidebar-about-section.tsx, src/components/ViewPackagePage/components/sidebar-releases-section.tsx, src/hooks/use-current-package-release.ts, src/pages/view-package.tsx
Multiple components were making duplicate API requests for the same package release data with different query parameters, causing unnecessary network requests:
- `view-package.tsx`: `include_ai_review: true`
- `sidebar-releases-section.tsx`: `include_ai_review: undefined`
- `sidebar-about-section.tsx`: `include_ai_review: undefined`
This resulted in duplicate requests like:
GET /api/package_releases/get?include_ai_review=true
GET /api/package_releases/get?include_ai_review=undefined
React Query treats different parameters as separate cache keys, so even though these components were fetching the same package release, React Query couldn't deduplicate the requests due to different `include_ai_review` values.
Refactored all components to use a shared `useCurrentPackageRelease` hook with …
=> fix: eliminate duplicate package release API requests

src/hooks/useUpdatePackageFilesMutation.ts
After deleting the file, the backend shows the file is not present. I checked the network request, the `/list` endpoint doesn't show it there too in the file system. But I can see the file being there in the editor even after a full reload of page cause the cache aren't being invalidated
https://github.com/user-attachments/assets/933e2f84-b486-49e2-8623-025a67c7e1de
=> refetches the latest editor content after saves.

fake-snippets-api/routes/api/orgs/list.ts, src/hooks/use-list-user-orgs.ts, src/pages/organization-settings.tsx, src/pages/user-profile.tsx
- Added `github_handle` as a common parameter in the organization listing API.
- Updated `useListUserOrgs` hook to accept an optional `githubHandle` parameter and adjusted API call accordingly.
- Modified the user profile page to pass the username as the `githubHandle` to `useListUserOrgs`.
- Simplified the NotFoundPage component usage in the organization settings page.
=> feat: user sepcific  organization listing

bun.lock, package.json
Bump Easyeda Version to add POLYGON pad support, to fix Bug with JLCPCB Part C2934569.
See [#easyeda-converter/324](https://github.com/tscircuit/easyeda-converter/issues/324)
=> Bump Easyeda Version to 0.0.228

package.json
Npm release failed for the last 10 workflows, but the git tags were created till 109
=> fix release of `fake-snippets` package

bun.lock, fake-snippets-api/routes/api/orgs/get.ts, fake-snippets-api/routes/api/orgs/list_members.ts, src/hooks/use-org-by-github-handle.ts
Fix org visibility issue where public org pages are not accessible for unauthenticated users. This PR updates the API routes to use optional auth instead and remove session req. from the org hook.
Fixes #1764
/claim #1764
=> Allow public org pages to be visible without session
