src/components/Header.tsx, src/components/HeaderDropdown.tsx
=> feat: add new dropdown

src/components/AiChatInterface.tsx, src/components/DownloadButtonAndMenu.tsx, src/components/EditorNav.tsx, src/components/SnippetLink.tsx, src/components/ViewSnippetSidebar.tsx, src/components/ui/toast.tsx, src/hooks/use-save-snippet.ts, src/pages/ai.tsx
- **wip**
- **many fixes and enhancements for ai chat**
=> AI Chat Improvements and Link Improvements

fake-snippets-api/lib/db/db-client.ts, fake-snippets-api/routes/api/snippets/search.ts, fake-snippets-api/tests/routes/snippets/search.test.ts, src/components/CodeAndPreview.tsx, src/components/dialogs/create-use-dialog.tsx, src/components/dialogs/import-snippet-dialog.tsx
- **bootstrap import dialog**
- **snippets search endpoint**
- **import snippet dialog initial, somewhat working**
=> Import Snippet Dialog

fake-snippets-api/lib/db/seed.ts, src/hooks/use-run-tsx/index.tsx
- **add replication in seed**
- **fix recursive importing**
=> Recursive Importing

src/components/EditorNav.tsx, src/components/dialogs/create-order-dialog.tsx
closes https://github.com/tscircuit/snippets/issues/71
- **Add CreateOrderDialog**
- **Add submit order button to editor nav bar**
=> Add Submit Order Button and Dialog

fake-snippets-api/lib/db/schema.ts, fake-snippets-api/lib/db/seed.ts, fake-snippets-api/routes/api/orders/create.ts, fake-snippets-api/routes/api/orders/update.ts, fake-snippets-api/tests/fixtures/get-test-server.ts, fake-snippets-api/tests/routes/order_files/upload.test.ts, src/components/OrderPreviewContent.tsx, src/pages/view-order.tsx
closes https://github.com/tscircuit/snippets/issues/70
=> Add order preview

src/components/ui/searchable-select.tsx
Closes https://github.com/tscircuit/snippets/issues/116
Before
https://github.com/user-attachments/assets/c31065b5-6500-49f4-8de7-0561aa150afd
After:
https://github.com/user-attachments/assets/98fa9c3d-2a31-4d58-a612-41e418ff6274
=> Fix SearchableSelect options width

src/components/ViewSnippetHeader.tsx
=> Implemented Fork on ViewSnippetHeader 

package.json, src/components/DownloadButtonAndMenu.tsx, src/lib/download-fns/download-schematic-svg.ts
=> Add Download Schematic SVG in download dropdown menu

src/components/Footer.tsx, src/pages/user-profile.tsx
Fix for #130:
Fix the profile page header to say "My Profile" when the current user is viewing their profile and fix the "My Profile" link in the footer to show up only when logged in.
=> fix(ui): fix ui for profile page header and footer "My profile" link

fake-snippets-api/lib/db/db-client.ts, fake-snippets-api/routes/api/snippets/update.ts, src/components/EditorNav.tsx
Added functionality to change snippet type
https://github.com/user-attachments/assets/eb3e2f78-66fa-4cfe-9360-53ee9c500489
NOTE: have made a few changes in the fake-snippets-api files, please let me know if they do not seem favorable
/claim #136 
cc: @seveibar
=> Change snippet type

package.json, src/hooks/use-run-tsx/index.tsx, src/lib/utils/getSyntaxError.ts
Closes #215 
I have added a util function and used it within the hook to return the react syntax error message.
/claim #215
=> feat: react typescript syntax error message

src/components/CircuitToSvgWithMouseControl.tsx
/claim #228
Fixes #228 
Video recording:
https://github.com/user-attachments/assets/2fa0a43f-79db-4459-ad8a-5038f889fb60
=> Fix: hovering over traces should change the colour

src/components/CodeEditor.tsx
Reverts tscircuit/snippets#250
@RohittCodes you caused a regression where every snippet has red underlines until you modify it
=> Revert: cursor pos

src/components/CodeAndPreview.tsx, src/components/PreviewContent.tsx, src/components/RunButton.tsx, src/hooks/use-run-tsx/index.tsx, src/pages/ai.tsx, src/pages/view-snippet.tsx
=> spinner on run button when running

src/hooks/use-current-snippet-id.ts
removed the delete operation for searchParams to make it persist during navigation.
fixes #195 
/claim #195
=> fix: template-url

src/components/CodeAndPreview.tsx, src/components/PreviewContent.tsx
=> feat: expand-preview

src/components/CodeEditor.tsx, src/lib/__tests__/constants.test.ts, src/lib/constants.ts
/claim #301
Fixes #301 
Screenshots:
=> fix:regex to import names with dash properly

src/App.tsx, src/pages/dev-login.tsx
https://github.com/user-attachments/assets/1da86938-17fa-4f20-877b-cd539c4b22d0
Logging in as **seveibar** 😂
=> feat: add the dev login page

src/components/CodeEditor.tsx, src/lib/constants.ts
Closes #313 
/claim #313
https://github.com/user-attachments/assets/18ce73c3-aff1-4a2b-8ac1-a411394dac8a
=> fix: Cmd Click is broken for clicking on snippets

bun-tests/fake-snippets-api/fixtures/get-test-server.ts
/claim #331
/closes #331
the random port generation is not so random, but why does it cause issues I thought these tests ran synchronously
=> fixed test falkiness

src/components/StaticPreviewContent.tsx, src/components/StaticViewSnippetHeader.tsx, src/components/StaticViewSnippetSidebar.tsx, src/pages/view-snippet.tsx
fixes #323 
To keep things simple, created new static components for loading view.
these components mimic the normal ones and look the same.
This is how it looks in loading mode
https://github.com/user-attachments/assets/9aa6c50c-766b-415f-a309-bbdfc1291593
/claim #323 
cc: @seveibar
=> added static skeleton page with fixed data

.github/workflows/bun-test.yml, .github/workflows/playwright-test.yml
=> increased playwright timeout

src/components/dialogs/rename-snippet-dialog.tsx
added a timeout and introduced a finally block
fixes: #295
/claim #295
=> fix: rename timeout

src/lib/codemirror/basic-setup.ts
fix multiple cursors when ctrl+click is triggered
close #321 
/claim #321
=> fix multiple cursors when ctrl+click is triggered

src/components/CircuitToSvgWithMouseControl.tsx, src/components/CodeAndPreview.tsx, src/components/PcbViewerWithContainerHeight.tsx, src/components/PreviewContent.tsx
fixes: #324 
/claim #324 
cc: @seveibar
=> feat: expand-to-full

playwright.config.ts
=> add retries for flaky test

playwright.config.ts, src/lib/__tests__/constants.test.ts, src/lib/constants.ts
=> fix: Regex to support underscore as well

src/lib/templates/blinking-led-board-template.ts
update blinking led circuit template
=> update blinking led circuit

README.md
=> added snippet example Arduino Nano Servo Breakout Board

fake-snippets-api/lib/db/autoload-dev-snippets.ts, fake-snippets-api/lib/db/autoload-snippets.json, fake-snippets-api/lib/db/seed.ts, package.json
https://github.com/user-attachments/assets/0d5c5192-9087-434a-beb2-de3f2a798ecb
/claim #174
/closes #174
=> import snippets from registry to development server

playwright-tests/view-snippet.spec.ts
=> add waitforLoadState to view-snippet.spec.ts test

src/components/EditorNav.tsx, src/components/ViewSnippetHeader.tsx, src/hooks/useForkSnippetMutation.ts
/claim #432 
Fixes #432 
reference video:
https://github.com/user-attachments/assets/f86c05a6-bfd3-44c7-9967-f2ec57ce3bd8
=> change save button to fork

index.html
- **improve seo**
- **add other seo keywords**
=> improve seo

src/components/FAQ.tsx, src/components/Header2.tsx, src/components/TrendingSnippetCarousel.tsx, src/pages/landing.tsx, tailwind.config.js
- **more landing page improvements**
- **improve FAQ**
=> Landing Page Improvements

src/pages/user-profile.tsx
/claim #449 
Fixes #449 
- Yes, it exist on production api
-
=> feat: Display number of stars for each snippet on profile page

src/pages/landing.tsx
=> improve landing feature bullet points on mobile

README.md
=> add algora bounty badge

src/components/SearchComponent.tsx
/claim #457 
Fixes #457 
https://github.com/user-attachments/assets/41c65850-399b-4a67-be75-808ef7376ca6
=> fix: search component

src/components/DownloadButtonAndMenu.tsx, src/lib/download-fns/download-assembly-svg.ts
=> add download Assembly svg button

src/components/ui/card.tsx
fixes #477 
@seveibar 
https://github.com/user-attachments/assets/441c5a5a-5c2e-4119-afca-88db28452637
=> fix card misalignment

src/components/ui/card.tsx
Reverts tscircuit/snippets#478
@techmannih this broke a bunch of pages, make sure to not change the ShadCN components, because it impacts every page
=> Revert "fix card misalignment"

playwright-tests/search-links.spec.ts, src/components/SearchComponent.tsx, src/pages/user-profile.tsx
=> improve search component

src/components/CodeEditor.tsx
=> Add type declaration for manual-edits.json in ATA

src/components/EditorNav.tsx, src/hooks/useForkSnippetMutation.ts
/claim #525 
Fixes #525 
###video:
https://github.com/user-attachments/assets/aef193dd-ea43-4162-81e7-40e29eb47513
=> fix: if somebody edits, then hits fork, we drop all their changes to the base snippet

playwright-tests/cmd-click.spec.ts, playwright-tests/editor-page.spec.ts, playwright-tests/preview-page.spec.ts
=> fix: timing issues in playwright

src/components/CreateNewSnippetWithAiHero.tsx
Fix text that goes out of the box 
issue: #534 
/claim #534
=> fix text box 

src/components/OptimizedImage.tsx, src/pages/landing.tsx
/claim #547 
Closes #547
Fixed image taking full width by giving them width, height and changing styles of OptimizedImage
=> fix: home page images

src/components/Header.tsx, src/components/Header2.tsx, src/components/HeaderLogin.tsx, src/components/SearchComponent.tsx, src/components/TrendingSnippetCarousel.tsx, src/pages/landing.tsx
100 accessibility score, and no more layout shift
=> some accessibility fields and eliminated layout shift on landing page

src/lib/templates/blank-package-template.ts
=> add useMychip hook

src/components/DownloadButtonAndMenu.tsx, src/lib/download-fns/download-gltf.ts
/claim #567 
Fixes #567 
video:
https://github.com/user-attachments/assets/bfbf2ccd-3e96-4df2-8ada-2b5f6e9acb49
=> fix: gltf downloader

fake-snippets-api/routes/api/snippets/images/[author]/[snippet_name]/[typeFormat].ts
=> feat: assembly image for snippets

bun.lock, package.json
/close https://github.com/tscircuit/core/issues/550
=> chore: update netlist library

src/components/dialogs/import-snippet-dialog.tsx
=> fix: encode the search params

index.html, src/App.tsx
=> add skeleton loader for landing page

index.html
=> change snippet background color to previous

scripts/generate_bundle_stats.js
=> fix: generate_bundle_stats.js

src/pages/editor.tsx
/fixes #653
https://github.com/user-attachments/assets/e0aa6b07-6a4a-401a-8830-923d2f2c0661
=> Fix: Update editor.tsx to handle screen overflow

src/components/HeaderLogin.tsx
/claim https://github.com/tscircuit/tscircuit.com/issues/549
Closes https://github.com/tscircuit/tscircuit.com/issues/549
Fixed for smaller device size 346x778
=> give space from right in get-start button for smaller size device

src/pages/landing.tsx
/claim #656
/fixes #656
https://github.com/user-attachments/assets/55897d75-3aca-490b-99d9-ffc2581c2734
=> Fix Github Badge Responsiveness

src/components/SnippetList.tsx, src/pages/dashboard.tsx
=> feat: Add show more/less btn in dashboard

src/components/CodeAndPreview.tsx
fixes #680 
/claim #680 
https://github.com/user-attachments/assets/6303df11-f92a-4faf-bbc9-f44bba24ce79
=> feat: show warning if the snippet is not saved

src/lib/templates/blinking-led-board-template.ts
=> fix: blinking led board template

bun-tests/fake-snippets-api/routes/package_files/create.test.ts, bun-tests/fake-snippets-api/routes/package_files/download.test.ts, bun-tests/fake-snippets-api/routes/package_files/get.test.ts, bun-tests/fake-snippets-api/routes/package_files/list.test.ts, fake-snippets-api/lib/db/db-client.ts, fake-snippets-api/lib/package_file/get-package-file-id-from-file-descriptor.ts, fake-snippets-api/lib/package_release/find-package-release-id.ts, fake-snippets-api/routes/api/package_files/create.ts, fake-snippets-api/routes/api/package_files/download.ts, fake-snippets-api/routes/api/package_files/get.ts, fake-snippets-api/routes/api/package_files/list.ts
Needed to test https://github.com/tscircuit/tscircuit.com/pull/692
=> add fake `package_files/` endpoint

src/components/ViewSnippetHeader.tsx
=> fix: Ensure isStarred state updates when snippet changes

src/components/CodeAndPreview.tsx, src/components/EditorNav.tsx, src/components/dialogs/package-visibility-settings-dialog.tsx, src/hooks/use-create-snippet-mutation.ts
=> feat: Dialog to choose package visibiilty

src/components/CodeAndPreview.tsx
=> fix: remove fixed board dimension for module

src/components/EditorNav.tsx
=> show menu only when the snippet is saved

package.json, src/components/SnippetTypeIcon.tsx, src/pages/user-profile.tsx
/claim https://github.com/tscircuit/tscircuit.com/issues/740
=> Improved bad alignment of packages page

fake-snippets-api/routes/api/_fake/db.ts
- **wip landing page**
- **initial footer**
- **add links to footer**
- **lots of bootstrapping for various pages**
- **add list_newest endpoint**
- **create newest page**
- **fix view snippet page**
- **wip dashboard**
- **wip dashboard**
- **implement /snippets/list**
- **implement dashboard edit recent**
- **save button**
- **implement hasUnsavedChanges**
- **move save button next to snippet**
- **wip**
- **better behaved header buttons**
- **starting view snippet page**
- **progress on view snippets page**
- **wip improve view snippet page**
- **wip start-editor page**
- **wip**
- **wip**
- **add templates and kicad import buttons**
- **load templates properly**
- **errors page**
- **add support for errors tab on codeandpreview**
- **add support for updated_at**
- **add no errors …
=> db debugger for fake

bun.lock, package.json, src/ContextProviders.tsx, src/pages/editor.tsx, src/pages/view-snippet.tsx
=> feat: add page title and image tag

src/pages/user-profile.tsx
=> feat: add user avatar and number of snippets in profile

fake-snippets-api/lib/db/autoload-dev-packages.ts, fake-snippets-api/routes/api/package_files/list.ts, src/components/ViewPackagePage/components/important-files-view.tsx, src/components/ViewPackagePage/utils/is-package-file-important.ts
Will have to add markdown support
=> Show README and update fake `/list` endpoint

src/components/ViewPackagePage/components/tab-views/files-view.tsx, src/components/ViewPackagePage/utils/is-hidden-file.ts
=> Hide lockfiles and config files.

.gitignore, src/App.tsx, src/pages/dashboard.tsx, src/pages/view-package.tsx
=> resolve Dashboard title issue

src/components/ViewPackagePage/components/mobile-sidebar.tsx, src/components/ViewPackagePage/components/preview-image-squares.tsx, src/hooks/use-preview-images.ts
=> Don't show schematic/pcb/3d view buttons if they aren't available for a package 

fake-snippets-api/lib/db/db-client.ts, fake-snippets-api/lib/db/schema.ts, fake-snippets-api/lib/public-mapping/public-map-package.ts, fake-snippets-api/routes/api/packages/create.ts, fake-snippets-api/routes/api/packages/update.ts, src/components/ViewPackagePage/components/mobile-sidebar.tsx, src/components/ViewPackagePage/components/sidebar-about-section.tsx, src/components/dialogs/edit-package-details-dialog.tsx
closes #807
https://github.com/user-attachments/assets/59f86bb5-57ba-46d2-8211-4f9ff0c82b97
=> feat(package-details): add edit package details dialog and update sidebar UI

src/components/ViewPackagePage/components/main-content-view-selector.tsx
=> feat: when json not avail, blank out the tabs

src/components/ViewPackagePage/components/tab-views/3d-view.tsx, src/components/ViewPackagePage/components/tab-views/schematic-view.tsx
=> feat: add clickToInteractEnabled prop

bun-tests/fake-snippets-api/routes/snippets/list_newest.test.ts, fake-snippets-api/lib/db/db-client.ts, fake-snippets-api/routes/api/snippets/list_latest.ts, scripts/generate-sitemap.ts, src/App.tsx, src/components/Footer.tsx, src/components/LatestSnippets.tsx, src/pages/dashboard.tsx, src/pages/latest.tsx, src/pages/newest.tsx
=> feat: add new format latest snippet page

src/components/EditorNav.tsx, src/hooks/use-delete-package.ts
=> Restricted 'Delete Snippet' and 'Change Package Visibility' button to owner only and fix error toast variant

fake-snippets-api/lib/db/db-client.ts, fake-snippets-api/routes/api/order_quote/create.ts, fake-snippets-api/routes/api/order_quote/create_all_vendor_quotes.ts, fake-snippets-api/routes/api/order_quote/get.ts
We can have a worker which will by the orderQuotes to process it, and we can poll on `/get` on the frontend to fetch the results of the quote
=> fake endpoint for `order_quotes`

src/hooks/use-fork-package-mutation.ts
=> fix(use-fork-package-mutation): handle error when forking own package

src/components/package-port/CodeEditor.tsx
The file selection logic in the useEffect hook was restructured to improve readability and maintainability. The nested conditions were flattened into a more linear flow, making it easier to follow the prioritization of file selection. This change does not alter the behavior but enhances the code's clarity.
resolve #877
=> refactor(CodeEditor): simplify file selection logic in useEffect

src/components/package-port/CodeEditor.tsx, src/components/package-port/CodeEditorHeader.tsx
=> Added file selector to /p/editor

src/components/ErrorOutline.tsx, src/components/FileSidebar.tsx, src/components/NotFound.tsx, src/components/dialogs/package-visibility-settings-dialog.tsx, src/components/package-port/CodeAndPreview.tsx, src/components/package-port/CodeEditor.tsx, src/components/package-port/CodeEditorHeader.tsx, src/pages/404.tsx, src/pages/package-editor.tsx
- Add `DialogDescription` to clarify package privacy settings a11y
- Replace basic error messages with `NotFound` and `ErrorOutline` components
- Introduce `pkgFilesLoaded` state to manage file loading in `CodeAndPreview`
- Improve file selection UI in `CodeEditorHeader` with better truncation and hidden file handling
- Refactor 404 page to use `NotFound` component for consistency
- Add fallback to select "index.ts" if no ".tsx" file is found in CodeEditor
- Update FileSidebar to handle hidden files correctly
- Validate packageId using UUID regex in package-editor
- Improve sidebar toggle button styling consistency
fix #883 
fix #885
=> feat: enhance UI and error handling in package editor

src/components/EditorNav.tsx, src/components/package-port/EditorNav.tsx
=> Restricted edit package name button to owner only

src/components/package-port/CodeEditorHeader.tsx, src/lib/utils/load-prettier.ts
Enhance the file formatting functionality by adding support for Markdown and HTML files. This includes loading additional Prettier parsers and improving file type detection logic to handle edge cases like empty files and files without extensions. Also, added error handling for unsupported file types and improved user feedback with descriptive toast messages.
=> refactor(CodeEditorHeader): add support for several file types formatting

src/pages/user-profile.tsx
https://github.com/user-attachments/assets/facd14b7-6101-43fd-bc08-0bc0f9774c40
fix #890
=> add filter to user profile

src/components/ViewPackagePage/utils/is-hidden-file.ts, src/components/package-port/CodeAndPreview.tsx, src/components/package-port/CodeEditor.tsx, src/lib/utils/findTargetFile.ts
Move the logic for finding the target file from the CodeEditor component into a separate utility function `findTargetFile` to improve code maintainability and reusability. This change also simplifies the component's useEffect logic.
- support old index.ts to render
=> refactor(CodeEditor): support tscircuit.config.json && extract file selection logic into utility function

src/components/package-port/CodeAndPreview.tsx
This change enhances the returned object by including all files from pkgFilesWithContent, improving the completeness of the data structure used in the component.
resolve #892
=> refactor(CodeAndPreview): add pkgFilesWithContent to returned object

src/pages/user-profile.tsx
Closes [Issue#872](https://github.com/tscircuit/tscircuit.com/issues/872)
Proof:
**Before:**
**After:**
https://github.com/user-attachments/assets/eff0ef2c-ba5d-41af-a60e-0d4a45affa23
=> fix: Added 'No starred packages' where there is no starred packages

src/components/PageSearchComponent.tsx, src/components/SearchComponent.tsx, src/pages/search.tsx
=> fix tscircuit.com/search

fake-snippets-api/lib/db/schema.ts, fake-snippets-api/routes/api/packages/add_star.ts, fake-snippets-api/routes/api/packages/list.ts, fake-snippets-api/routes/api/snippets/list.ts, src/pages/user-profile.tsx
fix #900 
/claim #900 
Packages can be sorted on based on most recently starred on user profile page.
[Screencast from 23-04-25 12:15:43 PM IST.webm](https://github.com/user-attachments/assets/00345bae-c5c6-4fba-adaa-93394820beda)
=> feat: Add star timestamp to snippets and update related logic

src/components/CodeEditor.tsx, src/hooks/use-shiki-highlighter.ts, src/index.css
=> Added syntax highlighting to the hover tooltip in code editor

src/components/ViewPackagePage/components/main-content-header.tsx, src/components/package-port/CodeAndPreview.tsx, src/components/package-port/EditorNav.tsx
@ArnavK-09
[fix(EditorNav): simplify save logic by removing unused props](https://github.com/tscircuit/tscircuit.com/pull/946/commits/01516b2ab9df9bdca392f9a64e369d71fdd4ce76)
=> fix(EditorNav): simplify save logic by removing unused props

bun-tests/fake-snippets-api/fixtures/get-test-server.ts, bun-tests/fake-snippets-api/routes/orders/order-with-circuit-json-or-package-release.test.ts, fake-snippets-api/lib/db/db-client.ts, fake-snippets-api/routes/api/order_quotes/create.ts
related to https://github.com/tscircuit/runframe/issues/505
=> Update fake to have /order_quotes/create accept circuit_json & test

fake-snippets-api/routes/api/order_quotes/create.ts, src/components/ViewPackagePage/components/markdown-viewer.tsx, src/index.css
=> fix: readme code syntax highlight

src/pages/user-profile.tsx
=> Show "No packages" when we don't have packages 

src/pages/dashboard.tsx
=> commented ai chat box and added snippetcard to show snippets on /dashboard

src/components/ViewPackagePage/components/package-header.tsx
https://github.com/user-attachments/assets/d87cd59e-c62a-4614-9bdf-fa01f20dac8a
Closes: [Issue#971](https://github.com/tscircuit/tscircuit.com/issues/971)
/claim #971
=> fix: removed fork from own package

src/components/CodeEditor.tsx
=> fixed ctrl/cmd prompt regression

src/components/ViewPackagePage/components/markdown-viewer.tsx
=> Added copy to clipboard option in readme code

bun-tests/fake-snippets-api/routes/package_releases/get.test.ts, fake-snippets-api/lib/db/schema.ts, fake-snippets-api/lib/public-mapping/public-map-package-release.ts, fake-snippets-api/routes/api/package_releases/create.ts, src/components/ViewPackagePage/components/build-status.tsx, src/components/ViewPackagePage/components/sidebar-releases-section.tsx
=> Add build status for the circuit-json

src/components/ViewPackagePage/components/package-header.tsx
Closes: [Issue#984](https://github.com/tscircuit/tscircuit.com/issues/984)
https://github.com/user-attachments/assets/0dc4fd22-ffea-4826-b75f-009af8e4ba40
=> added a tooltip in fork and star buttons if the user is not logged in

src/components/CodeAndPreview.tsx, src/components/package-port/CodeAndPreview.tsx
/claim  tscircuit/pcb-viewer#247
/closes  tscircuit/pcb-viewer#247
=> fixed rendering of double boards

src/components/package-port/CodeEditor.tsx
=> Added syntax highlighter to package-port/CodeEditor 

src/components/package-port/CodeAndPreview.tsx, src/hooks/useUpdatePackageFilesMutation.ts
=> refactor: simplify package file updates in CodeAndPreview component

src/components/PackageCard.tsx, src/components/SnippetTypeIcon.tsx, src/pages/trending.tsx
This commit introduces the new PackageCard component to display package information and updates the trending page to use packages instead of snippets. The SnippetType type is also exported for reuse in the PackageCard component.
=> feat: add PackageCard component and update trending page to use packages

src/components/ViewPackagePage/components/package-header.tsx
=> add order button for mobile

src/pages/trending.tsx
WIP
fix https://github.com/tscircuit/tscircuit.com/issues/1056
=> refactor(TrendingPage): remove unused refetch and keepPreviousData options from useQuery

src/pages/trending.tsx
Reverts tscircuit/tscircuit.com#1068
=> Revert "refactor(TrendingPage): remove unused refetch and keepPreviousData options from useQuery"

CONTRIBUTING.md, README.md, package.json, src/components/ErrorTabContent.tsx, src/components/ShippingInformationForm.tsx, src/components/ViewSnippetSidebar.tsx, src/hooks/use-toast.tsx
=> fix tscircuit.com repo link

src/components/ViewPackagePage/components/main-content-header.tsx
=> fix: dialog (dropdown) remains visible during navigation

src/components/ViewPackagePage/components/main-content-header.tsx
=> fix: unmounting of the dropdown item

src/components/ViewPackagePage/components/main-content-header.tsx
Reverts tscircuit/tscircuit.com#1095
=> Revert "fix: unmounting of the dropdown item"

src/components/HeaderLogin.tsx, src/components/ViewPackagePage/components/main-content-header.tsx
=> fix the annoying dropdown visible on redirect

src/components/Footer.tsx, src/components/PackageSearchResults.tsx, src/pages/search.tsx, src/pages/trending.tsx
- Added a new "Search Packages" link to the footer for improved navigation.
- Updated PackageSearchResults component to accept an emptyStateMessage prop for better user feedback when no packages are found.
- Refactored the SearchPage to manage search parameters and display results dynamically, including sorting options and search input handling.
- Enhanced the trending page to utilize the new emptyStateMessage for consistent messaging across search results.
fix https://github.com/tscircuit/tscircuit/issues/634
=> feat: add search functionality and enhance footer links

src/pages/quickstart.tsx
=> Update terminology in QuickstartPage to reflect package usage instead of snippets

src/components/ViewPackagePage/components/important-files-view.tsx
=> fix: important file preview not updating

bun-tests/fake-snippets-api/routes/packages/update.test.ts, fake-snippets-api/lib/db/schema.ts, fake-snippets-api/routes/api/packages/create.ts, fake-snippets-api/routes/api/packages/update.ts, src/components/ViewPackagePage/components/mobile-sidebar.tsx, src/components/ViewPackagePage/components/repo-page-content.tsx, src/components/ViewPackagePage/components/sidebar-about-section.tsx, src/components/dialogs/edit-package-details-dialog.tsx, src/hooks/use-package-details-form.ts, src/index.css
=> feat!: add default view functionality to package updates and create tests for validation

src/components/ViewPackagePage/components/repo-page-content.tsx
=> feat: add isPrivate prop to PackageHeader

src/components/package-port/CodeEditorHeader.tsx
fix #1137
(ignore lag at starting)
https://github.com/user-attachments/assets/1cdbd849-bddd-4739-878e-cfd5365c1ecc
=> patch: remove extra spacing

src/components/ViewPackagePage/components/important-files-view.tsx
=> fix: add overflow handling to important files view for better mobile experience

fake-snippets-api/routes/api/packages/get.ts, src/pages/package-editor.tsx, src/pages/view-package.tsx
=> feat: restrict access to private packages based on user session

src/components/package-port/CodeEditor.tsx
=> fix(CodeEditor): update decoration class to include cursor pointer for better user interaction

src/components/package-port/EditorNav.tsx
=> refactor(EditorNav): improve link presentation and accessibility by adding truncation and title attributes

src/lib/utils/checkIfManualEditsImported.ts
=> Enhance checkIfManualEditsImported function to include target file validation and improve logic for file type checks.

src/components/dialogs/import-package-dialog.tsx, src/components/package-port/CodeEditorHeader.tsx
=> refactor: temperory fix import snipet/package for editor

bun-tests/fake-snippets-api/routes/package_releases/create.test.ts, fake-snippets-api/lib/db/schema.ts, fake-snippets-api/lib/public-mapping/public-map-package-release.ts, fake-snippets-api/routes/api/package_releases/get.ts, fake-snippets-api/routes/api/package_releases/list.ts, src/hooks/use-current-package-release.ts, src/hooks/use-package-release.ts, src/pages/view-package.tsx
- **refactor to include logs when needed only**
- **force parameters to get ai review text (mimic real api)**
=> Get ai_review_text via include_ai_review=true

CONTRIBUTING.md, bun.lock, package.json, vite.config.ts
Reverts tscircuit/tscircuit.com#1265
=> Revert "updated runframe removing a nested dep(@tscircuit/eval)"

src/components/dialogs/edit-package-details-dialog.tsx
=> fix: error saving package name

src/components/ViewPackagePage/utils/is-package-file-important.ts
=> refactor: important files considering logic

src/components/ViewPackagePage/components/important-files-view.tsx, src/components/ViewPackagePage/components/repo-page-content.tsx, src/components/ViewPackagePage/utils/is-package-file-important.ts
=> refactor: important files considering logic and support readme w readme.md

src/pages/user-profile.tsx
=> fix: ensure safe access to github_username in user profile

src/components/Header.tsx, src/components/HeaderLogin.tsx
=> fix(ux): unusuable searching on mobile

src/components/dialogs/confirm-delete-package-dialog.tsx, src/components/dialogs/edit-package-details-dialog.tsx
=> margin Confirm Delete Package dialogue for smaller devies

src/components/dialogs/edit-package-details-dialog.tsx
=> fix: trim whitespace from unscoped package name input in edit package details dialog like github

api/generated-index.js
=> feat: desired og image preview type for package

src/components/DownloadButtonAndMenu.tsx
=> fix: update z-index for Download dropdown

src/components/ViewPackagePage/components/repo-page-content.tsx
=> feat: add releases section for small screens in repo page

src/components/CmdKMenu.tsx, src/components/package-port/CodeEditor.tsx, src/components/package-port/EditorNav.tsx, src/hooks/use-hotkey.ts
=> feat!: add useHotkey utility hook for keyboard shortcuts

src/components/ViewPackagePage/components/important-files-view.tsx
=> feat: implement file content client side caching in ImportantFilesView component

src/components/PackageCard.tsx
=> package native share option for devices

src/components/dialogs/view-ts-files-dialog.tsx
- Introduced a file tree structure to display TypeScript files and folders.
- Added search functionality to filter files based on user input.
- Integrated CodeMirror for viewing and editing file content with syntax highlighting.
- Implemented file statistics display, including total files and size.
- Enhanced UI with responsive sidebar and improved layout for better user experience.
=> Usable ViewTsFilesDialog to debug package files

src/components/dialogs/confirm-discard-changes-dialog.tsx, src/components/package-port/CodeAndPreview.tsx, src/components/package-port/EditorNav.tsx
https://github.com/user-attachments/assets/9a78ccd4-cd90-4ecb-9047-370396f0fbc5
=> Discard unsaved changes functionality to avoid reloading

src/components/CmdKMenu.tsx
=> Update fuzzy matching in CmdKMenu to include 'Import' prefix for better search relevance

src/App.tsx
Reverts tscircuit/tscircuit.com#1429
=> Revert "Revert "Fix reload logic for network errors""

src/components/package-port/CodeAndPreview.tsx
=> Prevent! runframe rerender, for mobile ux and dx

api/generated-index.js
=> Follow up fix for meta data coming undefined

src/components/PrefetchPageLink.tsx, src/hooks/use-account-balance.ts
=> fix the prefetch request being made due to bad url handling

bun.lock, package.json
=> fix: update schematic-symbols to fix Symbol not found schottky

src/components/package-port/CodeEditor.tsx, src/lib/constants.ts, src/lib/utils/resolveRelativePath.ts
=> feat(CodeEditor): support click to view local files for improts

src/components/ViewPackagePage/components/ShikiCodeViewer.tsx
=> fix: enhance loading state in ShikiCodeViewer with animated placeholders rather than plane text

src/components/package-port/CodeEditorHeader.tsx, src/hooks/useFileManagement.ts
=> fix: update file selection logic to handle hidden files in CodeEditorHeader and useFileManagement 

src/components/ViewPackagePage/components/important-files-view.tsx, src/components/dialogs/edit-package-details-dialog.tsx
=> fix: realtime changes for package details if file  changes on details  update

src/components/package-port/CodeEditorHeader.tsx
Import using JLCPCB Part Number.
EasyEDA Import uses Part Number
=> Fix JLCPCB Import

bun.lock, package.json, src/components/package-port/CodeAndPreview.tsx
=> Temporary fix the eval version to 0.0.264 until latest eval is stable

fake-snippets-api/lib/db/db-client.ts, fake-snippets-api/routes/api/accounts/search.ts, src/components/CmdKMenu.tsx
- Implement new API endpoint for account search
- Add account search results display in CmdK menu
=> feat!: add account search functionality to command menu + /accounts/search

src/components/FileSidebar.tsx
…
Reduce sidebar width from 34rem to 14rem when open and remove unnecessary red border color
=> style(FileSidebar): adjust sidebar width and remove redundant border color

src/components/preview/ConnectedRepoOverview.tsx, src/pages/404.tsx, src/pages/release-builds.tsx, src/pages/release-detail.tsx
- **wip**
- **no build information available**
=> More handling for package builds not being available

api/generated-index.js, src/App.tsx, src/components/FileSidebar.tsx, src/components/ViewPackagePage/components/sidebar-releases-section.tsx, src/components/preview/ConnectedPackagesList.tsx, src/components/preview/ConnectedRepoOverview.tsx, src/components/preview/PackageReleasesDashboard.tsx, src/lib/utils/transformFilesToTreeData.tsx, src/pages/preview-release.tsx, src/pages/release-builds.tsx, src/pages/release-detail.tsx
feat(preview): add new release preview page and loading states
refactor(files): extract file tree transformation logic to separate utility
fix(routing): update all preview and build links to use release-based URLs
=> refactor(preview): restructure preview functionality to use release-based URLs

src/components/package-port/CodeAndPreview.tsx, src/hooks/useUpdatePackageFilesMutation.ts
=> fix: skip hidden files in package file updates

src/components/ViewPackagePage/components/ShikiCodeViewer.tsx, src/components/ViewPackagePage/components/important-files-view.tsx
=> perf(important-files-view): optimize file content fetching, prevent multiple reqs and latency to load

src/components/package-port/EditorNav.tsx
=> Remove `undefined` text next to Dowload button

src/hooks/useFileManagement.ts, src/hooks/useOptimizedPackageFilesLoader.ts
=> fix: files not loading sometimes

src/components/CmdKMenu.tsx
=> style: fix  layout of CmdKMenu components

src/components/ViewPackagePage/components/main-content-view-selector.tsx
=> fix mobiel dropdown view

bun.lock, package.json, src/components/ViewPackagePage/components/tab-views/schematic-view.tsx
=> chore: update schematic-viewer dependency and disblae preview groups

bun.lock, package.json, src/components/DownloadButtonAndMenu.tsx, src/components/ViewPackagePage/components/main-content-header.tsx, src/components/package-port/EditorNav.tsx
fix #1634 
depends on https://github.com/tscircuit/schematic-viewer/pull/128 https://github.com/tscircuit/runframe/pull/1091
=> fix zindex overlapping issues & dep update

src/components/ViewPackagePage/components/mobile-sidebar.tsx, src/components/ViewPackagePage/components/preview-image-squares.tsx, src/hooks/use-package-release-images.ts, src/pages/release-detail.tsx
Reverts tscircuit/tscircuit.com#1640
=> Revert "Request 3D preview images as PNG"

src/components/ProfileRouter.tsx
=> fix(ProfileRouter): add check for non-personal organizations before rendering profile content

src/components/dialogs/rename-package-dialog.tsx, src/components/package-port/EditorNav.tsx
=> fix rename inconsistency

src/components/Header.tsx
Updated the layout of the Header component to improve responsiveness. Removed unnecessary list items and adjusted button visibility based on screen size.
=> Refactor Header component styling for medium screens, being overflowed previously

src/components/FileSidebar.tsx, src/components/ui/tree-view.tsx
https://github.com/user-attachments/assets/a8adfdad-716f-43ab-a0fb-3834e0c782b7
=> fix pos of actions for folders in editor

bun-tests/fake-snippets-api/fixtures/get-test-server.ts, bun-tests/fake-snippets-api/routes/orgs/create.test.ts, bun-tests/fake-snippets-api/routes/orgs/update.test.ts, fake-snippets-api/lib/db/db-client.ts, fake-snippets-api/lib/db/schema.ts, fake-snippets-api/lib/middleware/with-session-auth.ts, fake-snippets-api/lib/public-mapping/public-map-org.ts, fake-snippets-api/routes/api/orgs/create.ts, fake-snippets-api/routes/api/orgs/update.ts, fake-snippets-api/routes/api/packages/create.ts, src/pages/search.tsx
ref https://github.com/tscircuit/api.tscircuit.com/pull/716
=> feat: sync api to prod, org.org_name
